/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DineBrandWhereInput } from "./DineBrandWhereInput";
import { Type } from "class-transformer";
import { DineBrandOrderByInput } from "./DineBrandOrderByInput";

@ArgsType()
class DineBrandFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => DineBrandWhereInput,
  })
  @Field(() => DineBrandWhereInput, { nullable: true })
  @Type(() => DineBrandWhereInput)
  where?: DineBrandWhereInput;

  @ApiProperty({
    required: false,
    type: DineBrandOrderByInput,
  })
  @Field(() => DineBrandOrderByInput, { nullable: true })
  @Type(() => DineBrandOrderByInput)
  orderBy?: DineBrandOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { DineBrandFindManyArgs };
