/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteDineBrandArgs } from "./DeleteDineBrandArgs";
import { DineBrandFindManyArgs } from "./DineBrandFindManyArgs";
import { DineBrandFindUniqueArgs } from "./DineBrandFindUniqueArgs";
import { DineBrand } from "./DineBrand";
import { DineBrandService } from "../dineBrand.service";

@graphql.Resolver(() => DineBrand)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class DineBrandResolverBase {
  constructor(
    protected readonly service: DineBrandService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DineBrand",
    action: "read",
    possession: "any",
  })
  async _dineBrandsMeta(
    @graphql.Args() args: DineBrandFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [DineBrand])
  @nestAccessControl.UseRoles({
    resource: "DineBrand",
    action: "read",
    possession: "any",
  })
  async dineBrands(
    @graphql.Args() args: DineBrandFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DineBrand[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "DineBrand",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => DineBrand, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DineBrand",
    action: "read",
    possession: "own",
  })
  async dineBrand(
    @graphql.Args() args: DineBrandFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<DineBrand | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "DineBrand",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => DineBrand)
  @nestAccessControl.UseRoles({
    resource: "DineBrand",
    action: "delete",
    possession: "any",
  })
  async deleteDineBrand(
    @graphql.Args() args: DeleteDineBrandArgs
  ): Promise<DineBrand | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
