/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, DineBrand } from "@prisma/client";

export class DineBrandServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.DineBrandFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.DineBrandFindManyArgs>
  ): Promise<number> {
    return this.prisma.dineBrand.count(args);
  }

  async findMany<T extends Prisma.DineBrandFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.DineBrandFindManyArgs>
  ): Promise<DineBrand[]> {
    return this.prisma.dineBrand.findMany(args);
  }
  async findOne<T extends Prisma.DineBrandFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.DineBrandFindUniqueArgs>
  ): Promise<DineBrand | null> {
    return this.prisma.dineBrand.findUnique(args);
  }
  async create<T extends Prisma.DineBrandCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.DineBrandCreateArgs>
  ): Promise<DineBrand> {
    return this.prisma.dineBrand.create<T>(args);
  }
  async update<T extends Prisma.DineBrandUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.DineBrandUpdateArgs>
  ): Promise<DineBrand> {
    return this.prisma.dineBrand.update<T>(args);
  }
  async delete<T extends Prisma.DineBrandDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.DineBrandDeleteArgs>
  ): Promise<DineBrand> {
    return this.prisma.dineBrand.delete(args);
  }
}
